DROP TABLE POINT_LOG;
DROP TABLE T_BOARD;
DROP TABLE T_GOODS_DETAIL_IMAGE;
DROP TABLE T_IMAGEFILE;
DROP TABLE T_SHOPPING_CART;
DROP TABLE T_SHOPPING_GOODS;
DROP TABLE T_SHOPPING_ORDER;
DROP TABLE NOTICE_BOARD_IMG;
DROP TABLE FREE_BOARD_IMG;
DROP TABLE FREE_BOARD;
DROP TABLE QNA_BOARD_IMG;
DROP TABLE QNA_BOARD;
DROP TABLE REVIEW_BOARD_IMG;
DROP TABLE REVIEW_BOARD;
DROP TABLE NOTICE_BOARD;
DROP TABLE T_SHOPPING_MEMBER;



//T_GOODS_DETAIL_IMAGE테이블 생성
  CREATE TABLE "T_GOODS_DETAIL_IMAGE" 
   (	"IMAGE_ID" NUMBER(20,0), 
	"GOODS_ID" NUMBER(20,0), 
	"FILENAME" VARCHAR2(500 BYTE), 
	"REG_ID" VARCHAR2(20 BYTE), 
	"FILETYPE" VARCHAR2(40 BYTE), 
	"CREDATE" DATE DEFAULT sysdate, 
	"CATEGORY" VARCHAR2(20 BYTE), 
	 PRIMARY KEY ("IMAGE_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;

//T_IMAGEFILE테이블 생성

  CREATE TABLE "T_IMAGEFILE" 
   (	"IMAGEFILENO" NUMBER(10,0), 
	"IMAGEFILENAME" VARCHAR2(200 BYTE), 
	"REGDATE" DATE DEFAULT sysdate, 
	"ARTICLENO" NUMBER(10,0), 
	 PRIMARY KEY ("IMAGEFILENO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;

//T_SHOPPING_CART테이블 생성
  CREATE TABLE "T_SHOPPING_CART" 
   (	"CART_ID" NUMBER(10,0), 
	"GOODS_ID" NUMBER(20,0), 
	"MEMBER_ID" VARCHAR2(20 BYTE), 
	"DEL_YN" VARCHAR2(20 BYTE) DEFAULT 'N', 
	"CREDATE" DATE DEFAULT sysdate, 
	"CART_GOODS_QTY" NUMBER(4,0) DEFAULT 1, 
	 PRIMARY KEY ("CART_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;

//T_SHOPPING_GOODS테이블 생성

  CREATE TABLE "T_SHOPPING_GOODS" 
   (	"GOODS_ID" NUMBER(20,0), 
	"GOODS_SORT" VARCHAR2(50 BYTE), 
	"GOODS_TITLE" VARCHAR2(100 BYTE), 
	"GOODS_WRITER" VARCHAR2(50 BYTE), 
	"GOODS_PUBLISHER" VARCHAR2(50 BYTE), 
	"GOODS_PRICE" NUMBER(10,0), 
	"GOODS_SALES_PRICE" NUMBER(10,0), 
	"GOODS_POINT" NUMBER(10,0), 
	"GOODS_PUBLISHED_DATE" DATE, 
	"GOODS_TOTAL_PAGE" NUMBER(5,0), 
	"GOODS_ISBN" VARCHAR2(50 BYTE), 
	"GOODS_DELIVERY_PRICE" NUMBER(10,0), 
	"GOODS_DELIVERY_DATE" DATE, 
	"GOODS_STATUS" VARCHAR2(50 BYTE), 
	"GOODS_INTRO" VARCHAR2(2000 BYTE), 
	"GOODS_WRITER_INTRO" VARCHAR2(2000 BYTE), 
	"GOODS_PUBLISHER_COMMENT" VARCHAR2(2000 BYTE), 
	"GOODS_RECOMMENDATION" VARCHAR2(2000 BYTE), 
	"GOODS_CONTENTS_ORDER" CLOB, 
	"GOODS_CREDATE" DATE DEFAULT sysdate, 
	 PRIMARY KEY ("GOODS_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" 
 LOB ("GOODS_CONTENTS_ORDER") STORE AS BASICFILE (
  TABLESPACE "SYSTEM" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;

//T_SHOPPING_MEMBER테이블 생성

  CREATE TABLE "T_SHOPPING_MEMBER" 
   (	"MEMBER_ID" VARCHAR2(20 BYTE), 
	"MEMBER_PW" VARCHAR2(30 BYTE), 
	"MEMBER_NAME" VARCHAR2(50 BYTE), 
	"MEMBER_GENDER" VARCHAR2(10 BYTE), 
	"TEL1" VARCHAR2(20 BYTE), 
	"TEL2" VARCHAR2(20 BYTE), 
	"TEL3" VARCHAR2(20 BYTE), 
	"HP1" VARCHAR2(20 BYTE), 
	"HP2" VARCHAR2(20 BYTE), 
	"HP3" VARCHAR2(20 BYTE), 
	"SMSSTS_YN" VARCHAR2(20 BYTE), 
	"EMAIL1" VARCHAR2(20 BYTE), 
	"EMAIL2" VARCHAR2(20 BYTE), 
	"EMAILSTS_YN" VARCHAR2(20 BYTE), 
	"ZIPCODE" VARCHAR2(20 BYTE), 
	"ROADADDRESS" VARCHAR2(500 BYTE), 
	"JIBUNADDRESS" VARCHAR2(500 BYTE), 
	"NAMUJIADDRESS" VARCHAR2(500 BYTE), 
	"MEMBER_BIRTH_Y" VARCHAR2(20 BYTE), 
	"MEMBER_BIRTH_M" VARCHAR2(20 BYTE), 
	"MEMBER_BIRTH_D" VARCHAR2(20 BYTE), 
	"MEMBER_BIRTH_GN" VARCHAR2(20 BYTE), 
	"JOINDATE" DATE DEFAULT sysdate, 
	"DEL_YN" VARCHAR2(20 BYTE) DEFAULT 'N', 
	"ADMIN_YN" VARCHAR2(20 BYTE) DEFAULT 'N', 
	"MEMBER_POINT" NUMBER(10,0) DEFAULT 0, 
	 PRIMARY KEY ("MEMBER_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;

//T_SHOPPING_ORDER테이블생성
  CREATE TABLE "T_SHOPPING_ORDER" 
   (	"ORDER_SEQ_NUM" NUMBER(20,0), 
	"ORDER_ID" NUMBER(20,0), 
	"MEMBER_ID" VARCHAR2(20 BYTE), 
	"GOODS_ID" NUMBER(20,0), 
	"ORDERER_NAME" VARCHAR2(50 BYTE), 
	"GOODS_TITLE" VARCHAR2(100 BYTE), 
	"ORDER_GOODS_QTY" NUMBER(5,0), 
	"ORDER_GOODS_SIZE" NUMBER(3,0), 
	"GOODS_SALES_PRICE" NUMBER(5,0), 
	"GOODS_FILENAME" VARCHAR2(60 BYTE), 
	"RECEIVER_NAME" VARCHAR2(50 BYTE), 
	"RECEIVER_HP1" VARCHAR2(20 BYTE), 
	"RECEIVER_HP2" VARCHAR2(20 BYTE), 
	"RECEIVER_HP3" VARCHAR2(20 BYTE), 
	"RECEIVER_TEL1" VARCHAR2(20 BYTE), 
	"RECEIVER_TEL2" VARCHAR2(20 BYTE), 
	"RECEIVER_TEL3" VARCHAR2(20 BYTE), 
	"DELIVERY_ADDRESS" VARCHAR2(500 BYTE), 
	"DELIVERY_METHOD" VARCHAR2(40 BYTE), 
	"DELIVERY_MESSAGE" VARCHAR2(300 BYTE), 
	"GIFT_WRAPPING" VARCHAR2(20 BYTE), 
	"PAY_METHOD" VARCHAR2(200 BYTE), 
	"CARD_COM_NAME" VARCHAR2(50 BYTE), 
	"CARD_PAY_MONTH" VARCHAR2(20 BYTE), 
	"PAY_ORDERER_HP_NUM" VARCHAR2(20 BYTE), 
	"DELIVERY_STATE" VARCHAR2(20 BYTE) DEFAULT 'delivery_prepared', 
	"PAY_ORDER_TIME" DATE DEFAULT sysdate, 
	"ORDERER_HP" VARCHAR2(50 BYTE), 
	"DELIVERY_ZIPCODE" VARCHAR2(20 BYTE), 
	"DELIVERY_ROADADDRESS" VARCHAR2(500 BYTE), 
	"DELIVERY_JIBUNADDRESS" VARCHAR2(500 BYTE), 
	"DELIVERY_NAMUJIADDRESS" VARCHAR2(500 BYTE), 
	"ORDER_POINT" NUMBER(10,0) DEFAULT 0, 
	 PRIMARY KEY ("ORDER_SEQ_NUM")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;

// "FREE_BOARD테이블 생성
CREATE TABLE "FREE_BOARD" 
   (	"FREE_BO_NO" NUMBER(10,0) NOT NULL ENABLE, 
	"PARENT_NO" NUMBER(10,0) DEFAULT 0, 
	"MEM_ID" VARCHAR2(20 BYTE) NOT NULL ENABLE, 
	"TITLE" VARCHAR2(100 BYTE) NOT NULL ENABLE, 
	"CONTENT" VARCHAR2(4000 BYTE) NOT NULL ENABLE, 
	"READ_COUNT" NUMBER(30,0) DEFAULT 0, 
	"WRITE_DATE" DATE DEFAULT SYSDATE, 
	"IS_DEL" NUMBER(1,0) DEFAULT 0, 
	 CONSTRAINT "PK_FREE_BOARD" PRIMARY KEY ("FREE_BO_NO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE, 
	 CONSTRAINT "FK_FREE_BOARD" FOREIGN KEY ("MEM_ID")
	  REFERENCES "T_SHOPPING_MEMBER" ("MEMBER_ID") ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;

   COMMENT ON COLUMN "FREE_BOARD"."FREE_BO_NO" IS '글번호';
   COMMENT ON COLUMN "FREE_BOARD"."PARENT_NO" IS '부모 글 번호(DEFAULT 0)';
   COMMENT ON COLUMN "FREE_BOARD"."MEM_ID" IS '아이디';
   COMMENT ON COLUMN "FREE_BOARD"."TITLE" IS '글 제목';
   COMMENT ON COLUMN "FREE_BOARD"."CONTENT" IS '글 내용';
   COMMENT ON COLUMN "FREE_BOARD"."READ_COUNT" IS '조회수(DEFAULT 0)';
   COMMENT ON COLUMN "FREE_BOARD"."WRITE_DATE" IS '작성일(DEFAULT SYSDATE)';
   COMMENT ON COLUMN "FREE_BOARD"."IS_DEL" IS '삭제여부(DEFAULT 0 / 0:기본, 1:삭제)';
   COMMENT ON TABLE "FREE_BOARD"  IS '(FREE_BOARD)자유게시판';

// "FREE_BOARD_IMG테이블 생성
  CREATE TABLE "FREE_BOARD_IMG" 
   (	"FREE_BO_IMG_NO" NUMBER(10,0) NOT NULL ENABLE, 
	"FREE_BO_NO" NUMBER(10,0) NOT NULL ENABLE, 
	"IMG_FILENAME" VARCHAR2(200 BYTE) NOT NULL ENABLE, 
	"REG_DATE" DATE DEFAULT SYSDATE, 
	"IS_DEL" NUMBER(1,0) DEFAULT 0, 
	 CONSTRAINT "PK_FREE_BOARD_IMG" PRIMARY KEY ("FREE_BO_IMG_NO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE, 
	 CONSTRAINT "FK_FREE_BOARD_IMG" FOREIGN KEY ("FREE_BO_NO")
	  REFERENCES "FREE_BOARD" ("FREE_BO_NO") ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;

   COMMENT ON COLUMN "FREE_BOARD_IMG"."FREE_BO_IMG_NO" IS '자유게시판 이미지 파일 번호';
   COMMENT ON COLUMN "FREE_BOARD_IMG"."FREE_BO_NO" IS '글번호';
   COMMENT ON COLUMN "FREE_BOARD_IMG"."IMG_FILENAME" IS '이미지 파일 이름';
   COMMENT ON COLUMN "FREE_BOARD_IMG"."REG_DATE" IS '등록일(DEFAULT SYSDATE)';
   COMMENT ON COLUMN "FREE_BOARD_IMG"."IS_DEL" IS '삭제여부(DEFAULT 0 / 0:기본, 1:삭제)';
   COMMENT ON TABLE "FREE_BOARD_IMG"  IS '(FREE_BOARD_IMG)자유게시판 이미지';
   
   // "NOTICE_BOARD"테이블 생성
  CREATE TABLE "NOTICE_BOARD" 
   (	"NOTICE_BO_NO" NUMBER(10,0) NOT NULL ENABLE, 
	"PARENT_NO" NUMBER(10,0) DEFAULT 0, 
	"MEM_ID" VARCHAR2(20 BYTE) NOT NULL ENABLE, 
	"TITLE" VARCHAR2(100 BYTE) NOT NULL ENABLE, 
	"CONTENT" VARCHAR2(4000 BYTE) NOT NULL ENABLE, 
	"READ_COUNT" NUMBER(30,0) DEFAULT 0, 
	"WRITE_DATE" DATE DEFAULT SYSDATE, 
	"IS_DEL" NUMBER(1,0) DEFAULT 0, 
	 CONSTRAINT "PK_NOTICE_BOARD" PRIMARY KEY ("NOTICE_BO_NO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE, 
	 CONSTRAINT "FK_NOTICE_BOARD" FOREIGN KEY ("MEM_ID")
	  REFERENCES "T_SHOPPING_MEMBER" ("MEMBER_ID") ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;

   COMMENT ON COLUMN "NOTICE_BOARD"."NOTICE_BO_NO" IS '글번호';
   COMMENT ON COLUMN "NOTICE_BOARD"."PARENT_NO" IS '부모 글 번호(DEFAULT 0)';
   COMMENT ON COLUMN "NOTICE_BOARD"."MEM_ID" IS '아이디';
   COMMENT ON COLUMN "NOTICE_BOARD"."TITLE" IS '글 제목';
   COMMENT ON COLUMN "NOTICE_BOARD"."CONTENT" IS '글 내용';
   COMMENT ON COLUMN "NOTICE_BOARD"."READ_COUNT" IS '조회수(DEFAULT 0)';
   COMMENT ON COLUMN "NOTICE_BOARD"."WRITE_DATE" IS '작성일(DEFAULT SYSDATE)';
   COMMENT ON COLUMN "NOTICE_BOARD"."IS_DEL" IS '삭제여부(DEFAULT 0 / 0:기본, 1:삭제)';
   COMMENT ON TABLE "NOTICE_BOARD"  IS '(NOTICE_BOARD)공지사항 게시판';
   
   //"NOTICE_BOARD_IMG" 테이블생성
  CREATE TABLE "NOTICE_BOARD_IMG" 
   (	"NOTICE_BO_IMG_NO" NUMBER(10,0) NOT NULL ENABLE, 
	"NOTICE_BO_NO" NUMBER(10,0) NOT NULL ENABLE, 
	"IMG_FILENAME" VARCHAR2(200 BYTE) NOT NULL ENABLE, 
	"REG_DATE" DATE DEFAULT SYSDATE, 
	"IS_DEL" NUMBER(1,0) DEFAULT 0, 
	 CONSTRAINT "PK_NOTICE_BOARD_IMG" PRIMARY KEY ("NOTICE_BO_IMG_NO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE, 
	 CONSTRAINT "FK_NOTICE_BOARD_IMG" FOREIGN KEY ("NOTICE_BO_NO")
	  REFERENCES "NOTICE_BOARD" ("NOTICE_BO_NO") ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;

   COMMENT ON COLUMN "NOTICE_BOARD_IMG"."NOTICE_BO_IMG_NO" IS '공지사항 게시판 이미지 파일 번호';
   COMMENT ON COLUMN "NOTICE_BOARD_IMG"."NOTICE_BO_NO" IS '글번호';
   COMMENT ON COLUMN "NOTICE_BOARD_IMG"."IMG_FILENAME" IS '이미지 파일 이름';
   COMMENT ON COLUMN "NOTICE_BOARD_IMG"."REG_DATE" IS '등록일(DEFAULT SYSDATE)';
   COMMENT ON COLUMN "NOTICE_BOARD_IMG"."IS_DEL" IS '삭제여부(DEFAULT 0 / 0:기본, 1:삭제)';
   COMMENT ON TABLE "NOTICE_BOARD_IMG"  IS '(NOTICE_BOARD_IMG)공지사항 게시판 이미지';
   
   //POINT_LOG테이블 생성
  CREATE TABLE "POINT_LOG" 
   (	"POINT_LOG_NO" NUMBER(20,0) NOT NULL ENABLE, 
	"POINT_MONEY" NUMBER(20,0), 
	"SAVE_POINT_DATE" DATE DEFAULT sysdate, 
	"ORDER_SEQ_NUM" NUMBER(20,0), 
	"MEMBER_ID" VARCHAR2(20 BYTE) NOT NULL ENABLE, 
	"SAVE_YN" VARCHAR2(5 BYTE) DEFAULT 'N', 
	 CONSTRAINT "PK_POINT_LOG" PRIMARY KEY ("POINT_LOG_NO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE, 
	 CONSTRAINT "FK_POINT_LOG1" FOREIGN KEY ("ORDER_SEQ_NUM")
	  REFERENCES "T_SHOPPING_ORDER" ("ORDER_SEQ_NUM") ENABLE, 
	 CONSTRAINT "FK_POINT_LOG2" FOREIGN KEY ("MEMBER_ID")
	  REFERENCES "T_SHOPPING_MEMBER" ("MEMBER_ID") ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;

   COMMENT ON COLUMN "POINT_LOG"."POINT_LOG_NO" IS '포인트 일련번호';
   COMMENT ON COLUMN "POINT_LOG"."POINT_MONEY" IS '포인트 적립금';
   COMMENT ON COLUMN "POINT_LOG"."SAVE_POINT_DATE" IS '적립일자(default sysdate)';
   COMMENT ON COLUMN "POINT_LOG"."ORDER_SEQ_NUM" IS '주문번호';
   COMMENT ON COLUMN "POINT_LOG"."MEMBER_ID" IS '아이디';
   COMMENT ON COLUMN "POINT_LOG"."SAVE_YN" IS '적립여부(default N)';
   COMMENT ON TABLE "POINT_LOG"  IS '(POINT_LOG)포인트 적립 로그';

//QNA_BOARD테이블 생성
  CREATE TABLE "QNA_BOARD" 
   (	"QNA_BO_NO" NUMBER(10,0) NOT NULL ENABLE, 
	"PARENT_NO" NUMBER(10,0) DEFAULT 0, 
	"MEM_ID" VARCHAR2(20 BYTE) NOT NULL ENABLE, 
	"TITLE" VARCHAR2(100 BYTE) NOT NULL ENABLE, 
	"CONTENT" VARCHAR2(4000 BYTE) NOT NULL ENABLE, 
	"READ_COUNT" NUMBER(30,0) DEFAULT 0, 
	"WRITE_DATE" DATE DEFAULT SYSDATE, 
	"IS_DEL" NUMBER(1,0) DEFAULT 0, 
	 CONSTRAINT "PK_QNA_BOARD" PRIMARY KEY ("QNA_BO_NO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE, 
	 CONSTRAINT "FK_QNA_BOARD" FOREIGN KEY ("MEM_ID")
	  REFERENCES "T_SHOPPING_MEMBER" ("MEMBER_ID") ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;

   COMMENT ON COLUMN "QNA_BOARD"."QNA_BO_NO" IS '글번호';
   COMMENT ON COLUMN "QNA_BOARD"."PARENT_NO" IS '부모 글 번호(DEFAULT 0)';
   COMMENT ON COLUMN "QNA_BOARD"."MEM_ID" IS '아이디';
   COMMENT ON COLUMN "QNA_BOARD"."TITLE" IS '글 제목';
   COMMENT ON COLUMN "QNA_BOARD"."CONTENT" IS '글 내용';
   COMMENT ON COLUMN "QNA_BOARD"."READ_COUNT" IS '조회수(DEFAULT 0)';
   COMMENT ON COLUMN "QNA_BOARD"."WRITE_DATE" IS '작성일(DEFAULT SYSDATE)';
   COMMENT ON COLUMN "QNA_BOARD"."IS_DEL" IS '삭제여부(DEFAULT 0 / 0:기본, 1:삭제)';
   COMMENT ON TABLE "QNA_BOARD"  IS '(FREE_BOARD)자유게시판';
   
   //QNA_BOARD_IMG테이블 생성

  CREATE TABLE "QNA_BOARD_IMG" 
   (	"QNA_BO_IMG_NO" NUMBER(10,0) NOT NULL ENABLE, 
	"QNA_BO_NO" NUMBER(10,0) NOT NULL ENABLE, 
	"IMG_FILENAME" VARCHAR2(200 BYTE) NOT NULL ENABLE, 
	"REG_DATE" DATE DEFAULT SYSDATE, 
	"IS_DEL" NUMBER(1,0) DEFAULT 0, 
	 CONSTRAINT "PK_QNA_BOARD_IMG" PRIMARY KEY ("QNA_BO_IMG_NO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE, 
	 CONSTRAINT "FK_QNA_BOARD_IMG" FOREIGN KEY ("QNA_BO_NO")
	  REFERENCES "QNA_BOARD" ("QNA_BO_NO") ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;

   COMMENT ON COLUMN "QNA_BOARD_IMG"."QNA_BO_IMG_NO" IS '문의게시판 이미지 파일 번호';
   COMMENT ON COLUMN "QNA_BOARD_IMG"."QNA_BO_NO" IS '글번호';
   COMMENT ON COLUMN "QNA_BOARD_IMG"."IMG_FILENAME" IS '이미지 파일 이름';
   COMMENT ON COLUMN "QNA_BOARD_IMG"."REG_DATE" IS '등록일(DEFAULT SYSDATE)';
   COMMENT ON COLUMN "QNA_BOARD_IMG"."IS_DEL" IS '삭제여부(DEFAULT 0 / 0:기본, 1:삭제)';
   COMMENT ON TABLE "QNA_BOARD_IMG"  IS '(QNA_BOARD_IMG)문의게시판 이미지';
   
   //REVIEW_BOARD테이블 생성

  CREATE TABLE "REVIEW_BOARD" 
   (	"REVIEW_BO_NO" NUMBER(10,0) NOT NULL ENABLE, 
	"PARENT_NO" NUMBER(10,0) DEFAULT 0, 
	"MEM_ID" VARCHAR2(20 BYTE) NOT NULL ENABLE, 
	"TITLE" VARCHAR2(100 BYTE) NOT NULL ENABLE, 
	"CONTENT" VARCHAR2(4000 BYTE) NOT NULL ENABLE, 
	"READ_COUNT" NUMBER(30,0) DEFAULT 0, 
	"WRITE_DATE" DATE DEFAULT SYSDATE, 
	"IS_DEL" NUMBER(1,0) DEFAULT 0, 
	 CONSTRAINT "PK_REVIEW_BOARD" PRIMARY KEY ("REVIEW_BO_NO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE, 
	 CONSTRAINT "FK_REVIEW_BOARD" FOREIGN KEY ("MEM_ID")
	  REFERENCES "T_SHOPPING_MEMBER" ("MEMBER_ID") ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;

   COMMENT ON COLUMN "REVIEW_BOARD"."REVIEW_BO_NO" IS '글번호';
   COMMENT ON COLUMN "REVIEW_BOARD"."PARENT_NO" IS '부모 글 번호(DEFAULT 0)';
   COMMENT ON COLUMN "REVIEW_BOARD"."MEM_ID" IS '아이디';
   COMMENT ON COLUMN "REVIEW_BOARD"."TITLE" IS '글 제목';
   COMMENT ON COLUMN "REVIEW_BOARD"."CONTENT" IS '글 내용';
   COMMENT ON COLUMN "REVIEW_BOARD"."READ_COUNT" IS '조회수(DEFAULT 0)';
   COMMENT ON COLUMN "REVIEW_BOARD"."WRITE_DATE" IS '작성일(DEFAULT SYSDATE)';
   COMMENT ON COLUMN "REVIEW_BOARD"."IS_DEL" IS '삭제여부(DEFAULT 0 / 0:기본, 1:삭제)';
   COMMENT ON TABLE "REVIEW_BOARD"  IS '(REVIEW_BOARD)상품후기게시판';
   //REVIEW_BOARD_IMG테이블생성

  CREATE TABLE "REVIEW_BOARD_IMG" 
   (	"REVIEW_BO_IMG_NO" NUMBER(10,0) NOT NULL ENABLE, 
	"REVIEW_BO_NO" NUMBER(10,0) NOT NULL ENABLE, 
	"IMG_FILENAME" VARCHAR2(200 BYTE) NOT NULL ENABLE, 
	"REG_DATE" DATE DEFAULT SYSDATE, 
	"IS_DEL" NUMBER(1,0) DEFAULT 0, 
	 CONSTRAINT "PK_REVIEW_BOARD_IMG" PRIMARY KEY ("REVIEW_BO_IMG_NO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE, 
	 CONSTRAINT "FK_REVIEW_BOARD_IMG" FOREIGN KEY ("REVIEW_BO_NO")
	  REFERENCES "REVIEW_BOARD" ("REVIEW_BO_NO") ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;

   COMMENT ON COLUMN "REVIEW_BOARD_IMG"."REVIEW_BO_IMG_NO" IS '상품후기게시판 이미지 파일 번호';
   COMMENT ON COLUMN "REVIEW_BOARD_IMG"."REVIEW_BO_NO" IS '글번호';
   COMMENT ON COLUMN "REVIEW_BOARD_IMG"."IMG_FILENAME" IS '이미지 파일 이름';
   COMMENT ON COLUMN "REVIEW_BOARD_IMG"."REG_DATE" IS '등록일(DEFAULT SYSDATE)';
   COMMENT ON COLUMN "REVIEW_BOARD_IMG"."IS_DEL" IS '삭제여부(DEFAULT 0 / 0:기본, 1:삭제)';
   COMMENT ON TABLE "REVIEW_BOARD_IMG"  IS '(REVIEW_BOARD_IMG)상품후기게시판 이미지';
   
   //T_BOARD테이블 생성
  CREATE TABLE "T_BOARD" 
   (	"ARTICLENO" NUMBER(10,0), 
	"PARENTNO" NUMBER(10,0) DEFAULT 0, 
	"TITLE" VARCHAR2(500 BYTE) NOT NULL ENABLE, 
	"CONTENT" VARCHAR2(4000 BYTE), 
	"IMAGEFILENAME" VARCHAR2(30 BYTE), 
	"WRITEDATE" DATE DEFAULT sysdate NOT NULL ENABLE, 
	"ID" VARCHAR2(10 BYTE), 
	 PRIMARY KEY ("ARTICLENO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE, 
	 CONSTRAINT "FK_ID" FOREIGN KEY ("ID")
	  REFERENCES "T_SHOPPING_MEMBER" ("MEMBER_ID") ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;

--T_SHOPPING_GOODS  
Insert into T_SHOPPING_GOODS (GOODS_ID,GOODS_SORT,GOODS_TITLE,GOODS_WRITER,GOODS_PUBLISHER,GOODS_PRICE,GOODS_SALES_PRICE,GOODS_POINT,GOODS_PUBLISHED_DATE,GOODS_TOTAL_PAGE,GOODS_ISBN,GOODS_DELIVERY_PRICE,GOODS_DELIVERY_DATE,GOODS_STATUS,GOODS_INTRO,GOODS_WRITER_INTRO,GOODS_PUBLISHER_COMMENT,GOODS_RECOMMENDATION,GOODS_CREDATE) values (1,'나이키','나이키_코트 버로우 로우 2','나이키 코리아','made in korea',32000,32000,1000,to_date('18/08/01','RR/MM/DD'),688,'9791160505238',2000,to_date('18/10/17','RR/MM/DD'),'nike','나이키 코리아','나이키 코리아','나이키 코리아','나이키 코리아',to_date('18/10/16','RR/MM/DD'));
Insert into T_SHOPPING_GOODS (GOODS_ID,GOODS_SORT,GOODS_TITLE,GOODS_WRITER,GOODS_PUBLISHER,GOODS_PRICE,GOODS_SALES_PRICE,GOODS_POINT,GOODS_PUBLISHED_DATE,GOODS_TOTAL_PAGE,GOODS_ISBN,GOODS_DELIVERY_PRICE,GOODS_DELIVERY_DATE,GOODS_STATUS,GOODS_INTRO,GOODS_WRITER_INTRO,GOODS_PUBLISHER_COMMENT,GOODS_RECOMMENDATION,GOODS_CREDATE) values (2,'나이키','나이키_에어맥스 SC 레더','나이키 코리아','made in korea',22000,19800,1000,to_date('18/05/22','RR/MM/DD'),336,'9791160504736',2000,to_date('18/10/17','RR/MM/DD'),'nike','나이키 코리아','나이키 코리아','나이키 코리아','나이키 코리아',to_date('18/10/16','RR/MM/DD'));
Insert into T_SHOPPING_GOODS (GOODS_ID,GOODS_SORT,GOODS_TITLE,GOODS_WRITER,GOODS_PUBLISHER,GOODS_PRICE,GOODS_SALES_PRICE,GOODS_POINT,GOODS_PUBLISHED_DATE,GOODS_TOTAL_PAGE,GOODS_ISBN,GOODS_DELIVERY_PRICE,GOODS_DELIVERY_DATE,GOODS_STATUS,GOODS_INTRO,GOODS_WRITER_INTRO,GOODS_PUBLISHER_COMMENT,GOODS_RECOMMENDATION,GOODS_CREDATE) values (3,'나이키','나이키_버로우 패딩 겨울 슬리퍼','나이키 코리아','made in korea',34000,30000,1000,to_date('18/10/02','RR/MM/DD'),1111,'12122222',2000,to_date('18/10/17','RR/MM/DD'),'nike','나이키 코리아','나이키 코리아','나이키 코리아','나이키 코리아',to_date('18/10/16','RR/MM/DD'));
Insert into T_SHOPPING_GOODS (GOODS_ID,GOODS_SORT,GOODS_TITLE,GOODS_WRITER,GOODS_PUBLISHER,GOODS_PRICE,GOODS_SALES_PRICE,GOODS_POINT,GOODS_PUBLISHED_DATE,GOODS_TOTAL_PAGE,GOODS_ISBN,GOODS_DELIVERY_PRICE,GOODS_DELIVERY_DATE,GOODS_STATUS,GOODS_INTRO,GOODS_WRITER_INTRO,GOODS_PUBLISHER_COMMENT,GOODS_RECOMMENDATION,GOODS_CREDATE) values (10,'뉴발란스','뉴발란스_WL574','뉴발란스 코리아','made in korea',1212,30000,121,to_date('18/10/02','RR/MM/DD'),12,'1212',2000,to_date('18/10/24','RR/MM/DD'),'newbalance','뉴발란스 코리아','뉴발란스 코리아','뉴발란스 코리아','뉴발란스 코리아',to_date('18/10/16','RR/MM/DD'));
Insert into T_SHOPPING_GOODS (GOODS_ID,GOODS_SORT,GOODS_TITLE,GOODS_WRITER,GOODS_PUBLISHER,GOODS_PRICE,GOODS_SALES_PRICE,GOODS_POINT,GOODS_PUBLISHED_DATE,GOODS_TOTAL_PAGE,GOODS_ISBN,GOODS_DELIVERY_PRICE,GOODS_DELIVERY_DATE,GOODS_STATUS,GOODS_INTRO,GOODS_WRITER_INTRO,GOODS_PUBLISHER_COMMENT,GOODS_RECOMMENDATION,GOODS_CREDATE) values (11,'뉴발란스','뉴발란스_MS237','뉴발란스 코리아','made in korea',30000,30000,1212,to_date('18/10/02','RR/MM/DD'),1212,'1212',1212,to_date('18/10/18','RR/MM/DD'),'newbalance','뉴발란스 코리아','뉴발란스 코리아','뉴발란스 코리아','뉴발란스 코리아',to_date('18/10/17','RR/MM/DD'));
Insert into T_SHOPPING_GOODS (GOODS_ID,GOODS_SORT,GOODS_TITLE,GOODS_WRITER,GOODS_PUBLISHER,GOODS_PRICE,GOODS_SALES_PRICE,GOODS_POINT,GOODS_PUBLISHED_DATE,GOODS_TOTAL_PAGE,GOODS_ISBN,GOODS_DELIVERY_PRICE,GOODS_DELIVERY_DATE,GOODS_STATUS,GOODS_INTRO,GOODS_WRITER_INTRO,GOODS_PUBLISHER_COMMENT,GOODS_RECOMMENDATION,GOODS_CREDATE) values (12,'뉴발란스','뉴발란스_CM878','뉴발란스 코리아','made in korea',30000,30000,1212,to_date('18/10/02','RR/MM/DD'),1212,'1212',1212,to_date('18/10/19','RR/MM/DD'),'newbalance','뉴발란스 코리아','뉴발란스 코리아','뉴발란스 코리아','뉴발란스 코리아',to_date('18/10/17','RR/MM/DD'));
Insert into T_SHOPPING_GOODS (GOODS_ID,GOODS_SORT,GOODS_TITLE,GOODS_WRITER,GOODS_PUBLISHER,GOODS_PRICE,GOODS_SALES_PRICE,GOODS_POINT,GOODS_PUBLISHED_DATE,GOODS_TOTAL_PAGE,GOODS_ISBN,GOODS_DELIVERY_PRICE,GOODS_DELIVERY_DATE,GOODS_STATUS,GOODS_INTRO,GOODS_WRITER_INTRO,GOODS_PUBLISHER_COMMENT,GOODS_RECOMMENDATION,GOODS_CREDATE) values (6,'아디다스','아디다스_슈퍼스타','아디다스 코리아','made in korea',25000,25000,1212,to_date('18/08/08','RR/MM/DD'),1212,'1212',1212,to_date('18/10/26','RR/MM/DD'),'adidas','아디다스 코리아','아디다스 코리아','아디다스 코리아','아디다스 코리아',to_date('18/10/17','RR/MM/DD'));
Insert into T_SHOPPING_GOODS (GOODS_ID,GOODS_SORT,GOODS_TITLE,GOODS_WRITER,GOODS_PUBLISHER,GOODS_PRICE,GOODS_SALES_PRICE,GOODS_POINT,GOODS_PUBLISHED_DATE,GOODS_TOTAL_PAGE,GOODS_ISBN,GOODS_DELIVERY_PRICE,GOODS_DELIVERY_DATE,GOODS_STATUS,GOODS_INTRO,GOODS_WRITER_INTRO,GOODS_PUBLISHER_COMMENT,GOODS_RECOMMENDATION,GOODS_CREDATE) values (4,'아디다스','아디다스_아스티어우먼스','아디다스 코리아','made in korea',25000,25000,1212,to_date('18/10/29','RR/MM/DD'),1212,'1212',1212,to_date('18/10/25','RR/MM/DD'),'adidas','아디다스 코리아','아디다스 코리아','아디다스 코리아','아디다스 코리아',to_date('18/10/17','RR/MM/DD'));
Insert into T_SHOPPING_GOODS (GOODS_ID,GOODS_SORT,GOODS_TITLE,GOODS_WRITER,GOODS_PUBLISHER,GOODS_PRICE,GOODS_SALES_PRICE,GOODS_POINT,GOODS_PUBLISHED_DATE,GOODS_TOTAL_PAGE,GOODS_ISBN,GOODS_DELIVERY_PRICE,GOODS_DELIVERY_DATE,GOODS_STATUS,GOODS_INTRO,GOODS_WRITER_INTRO,GOODS_PUBLISHER_COMMENT,GOODS_RECOMMENDATION,GOODS_CREDATE) values (5,'아디다스','아디다스_스탠스미스','아디다스 코리아','made in korea',25000,25000,1212,to_date('18/10/17','RR/MM/DD'),1212,'1212',1212,to_date('18/10/25','RR/MM/DD'),'adidas','아디다스 코리아','아디다스 코리아','아디다스 코리아','아디다스 코리아',to_date('18/10/17','RR/MM/DD'));
Insert into T_SHOPPING_GOODS (GOODS_ID,GOODS_SORT,GOODS_TITLE,GOODS_WRITER,GOODS_PUBLISHER,GOODS_PRICE,GOODS_SALES_PRICE,GOODS_POINT,GOODS_PUBLISHED_DATE,GOODS_TOTAL_PAGE,GOODS_ISBN,GOODS_DELIVERY_PRICE,GOODS_DELIVERY_DATE,GOODS_STATUS,GOODS_INTRO,GOODS_WRITER_INTRO,GOODS_PUBLISHER_COMMENT,GOODS_RECOMMENDATION,GOODS_CREDATE) values (13,'아식스','아식스_코트S','아식스 코리아','made in korea',25000,25000,2222,to_date('18/10/18','RR/MM/DD'),2222,'2222',2222,to_date('18/10/18','RR/MM/DD'),'asics','아식스 코리아','아식스 코리아','아식스 코리아','아식스 코리아',to_date('18/10/17','RR/MM/DD'));
Insert into T_SHOPPING_GOODS (GOODS_ID,GOODS_SORT,GOODS_TITLE,GOODS_WRITER,GOODS_PUBLISHER,GOODS_PRICE,GOODS_SALES_PRICE,GOODS_POINT,GOODS_PUBLISHED_DATE,GOODS_TOTAL_PAGE,GOODS_ISBN,GOODS_DELIVERY_PRICE,GOODS_DELIVERY_DATE,GOODS_STATUS,GOODS_INTRO,GOODS_WRITER_INTRO,GOODS_PUBLISHER_COMMENT,GOODS_RECOMMENDATION,GOODS_CREDATE) values (14,'아식스','아식스_조그 100T우먼스','아식스 코리아','made in korea',20000,20000,5555,to_date('18/10/04','RR/MM/DD'),555,'555',555,to_date('18/10/11','RR/MM/DD'),'asics','아식스 코리아','아식스 코리아','아식스 코리아','아식스 코리아',to_date('18/10/17','RR/MM/DD'));
Insert into T_SHOPPING_GOODS (GOODS_ID,GOODS_SORT,GOODS_TITLE,GOODS_WRITER,GOODS_PUBLISHER,GOODS_PRICE,GOODS_SALES_PRICE,GOODS_POINT,GOODS_PUBLISHED_DATE,GOODS_TOTAL_PAGE,GOODS_ISBN,GOODS_DELIVERY_PRICE,GOODS_DELIVERY_DATE,GOODS_STATUS,GOODS_INTRO,GOODS_WRITER_INTRO,GOODS_PUBLISHER_COMMENT,GOODS_RECOMMENDATION,GOODS_CREDATE) values (15,'아식스','아식스_젤 벤쳐6','아식스 코리아','made in korea',30000,30000,777,to_date('18/10/04','RR/MM/DD'),990,'777',2000,to_date('18/11/22','RR/MM/DD'),'asics','아식스 코리아','아식스 코리아','아식스 코리아','아식스 코리아',to_date('18/10/17','RR/MM/DD'));
Insert into T_SHOPPING_GOODS (GOODS_ID,GOODS_SORT,GOODS_TITLE,GOODS_WRITER,GOODS_PUBLISHER,GOODS_PRICE,GOODS_SALES_PRICE,GOODS_POINT,GOODS_PUBLISHED_DATE,GOODS_TOTAL_PAGE,GOODS_ISBN,GOODS_DELIVERY_PRICE,GOODS_DELIVERY_DATE,GOODS_STATUS,GOODS_INTRO,GOODS_WRITER_INTRO,GOODS_PUBLISHER_COMMENT,GOODS_RECOMMENDATION,GOODS_CREDATE) values (16,'퓨마','퓨마_스카이클린','퓨마 코리아','made in korea',30000,27000,2000,to_date('18/10/02','RR/MM/DD'),996,'2323454566778',2000,to_date('18/10/18','RR/MM/DD'),'puma','퓨마 코리아','퓨마 코리아','퓨마 코리아','퓨마 코리아',to_date('18/10/17','RR/MM/DD'));
Insert into T_SHOPPING_GOODS (GOODS_ID,GOODS_SORT,GOODS_TITLE,GOODS_WRITER,GOODS_PUBLISHER,GOODS_PRICE,GOODS_SALES_PRICE,GOODS_POINT,GOODS_PUBLISHED_DATE,GOODS_TOTAL_PAGE,GOODS_ISBN,GOODS_DELIVERY_PRICE,GOODS_DELIVERY_DATE,GOODS_STATUS,GOODS_INTRO,GOODS_WRITER_INTRO,GOODS_PUBLISHER_COMMENT,GOODS_RECOMMENDATION,GOODS_CREDATE) values (17,'퓨마','퓨마_스웨이드클래식','퓨마 코리아','made in korea',30000,30000,888,to_date('18/10/12','RR/MM/DD'),888,'8888',888,to_date('18/10/18','RR/MM/DD'),'puma','퓨마 코리아','퓨마 코리아','퓨마 코리아','퓨마 코리아',to_date('18/10/17','RR/MM/DD'));
Insert into T_SHOPPING_GOODS (GOODS_ID,GOODS_SORT,GOODS_TITLE,GOODS_WRITER,GOODS_PUBLISHER,GOODS_PRICE,GOODS_SALES_PRICE,GOODS_POINT,GOODS_PUBLISHED_DATE,GOODS_TOTAL_PAGE,GOODS_ISBN,GOODS_DELIVERY_PRICE,GOODS_DELIVERY_DATE,GOODS_STATUS,GOODS_INTRO,GOODS_WRITER_INTRO,GOODS_PUBLISHER_COMMENT,GOODS_RECOMMENDATION,GOODS_CREDATE) values (18,'퓨마','퓨마_그래비톤','퓨마 코리아','made in korea',30000,30000,898,to_date('18/10/23','RR/MM/DD'),8989,'8989',8989,to_date('18/10/18','RR/MM/DD'),'puma','퓨마 코리아','퓨마 코리아','퓨마 코리아','퓨마 코리아',to_date('18/10/17','RR/MM/DD'));
Insert into T_SHOPPING_GOODS (GOODS_ID,GOODS_SORT,GOODS_TITLE,GOODS_WRITER,GOODS_PUBLISHER,GOODS_PRICE,GOODS_SALES_PRICE,GOODS_POINT,GOODS_PUBLISHED_DATE,GOODS_TOTAL_PAGE,GOODS_ISBN,GOODS_DELIVERY_PRICE,GOODS_DELIVERY_DATE,GOODS_STATUS,GOODS_INTRO,GOODS_WRITER_INTRO,GOODS_PUBLISHER_COMMENT,GOODS_RECOMMENDATION,GOODS_CREDATE) values (19,'필라','필라_유니바스티온','필라 코리아','made in korea',30000,32400,2000,to_date('18/10/17','RR/MM/DD'),1111,'1212121',2000,to_date('18/10/22','RR/MM/DD'),'fila','필라 코리아','필라 코리아','필라 코리아','필라 코리아',to_date('18/10/20','RR/MM/DD'));
Insert into T_SHOPPING_GOODS (GOODS_ID,GOODS_SORT,GOODS_TITLE,GOODS_WRITER,GOODS_PUBLISHER,GOODS_PRICE,GOODS_SALES_PRICE,GOODS_POINT,GOODS_PUBLISHED_DATE,GOODS_TOTAL_PAGE,GOODS_ISBN,GOODS_DELIVERY_PRICE,GOODS_DELIVERY_DATE,GOODS_STATUS,GOODS_INTRO,GOODS_WRITER_INTRO,GOODS_PUBLISHER_COMMENT,GOODS_RECOMMENDATION,GOODS_CREDATE) values (20,'필라','필라_레인저','필라 코리아','made in korea',34000,30000,1000,to_date('18/10/18','RR/MM/DD'),1212,'12122222',2000,to_date('18/10/24','RR/MM/DD'),'fila','필라 코리아','필라 코리아','필라 코리아','필라 코리아',to_date('18/10/20','RR/MM/DD'));
Insert into T_SHOPPING_GOODS (GOODS_ID,GOODS_SORT,GOODS_TITLE,GOODS_WRITER,GOODS_PUBLISHER,GOODS_PRICE,GOODS_SALES_PRICE,GOODS_POINT,GOODS_PUBLISHED_DATE,GOODS_TOTAL_PAGE,GOODS_ISBN,GOODS_DELIVERY_PRICE,GOODS_DELIVERY_DATE,GOODS_STATUS,GOODS_INTRO,GOODS_WRITER_INTRO,GOODS_PUBLISHER_COMMENT,GOODS_RECOMMENDATION,GOODS_CREDATE) values (21,'필라','필라_레이폴라이드','필라 코리아','made in korea',34000,30000,1000,to_date('18/10/02','RR/MM/DD'),1111,'12122222',2000,to_date('18/10/25','RR/MM/DD'),'fila','필라 코리아','필라 코리아','필라 코리아','필라 코리아',to_date('18/10/20','RR/MM/DD'));
--------------------------------------------------------
--  DDL for Index SYS_C0010493
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYS_C0010493" ON "T_SHOPPING_GOODS" ("GOODS_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table T_SHOPPING_GOODS
--------------------------------------------------------

  ALTER TABLE "T_SHOPPING_GOODS" ADD PRIMARY KEY ("GOODS_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;

--T_GOODS_DETAIL_IMAGE
Insert into T_GOODS_DETAIL_IMAGE (IMAGE_ID,GOODS_ID,FILENAME,REG_ID,FILETYPE,CREDATE,CATEGORY) values (346,1,'나이키_코트 버로우 로우 2.jpg','admin','main_image',to_date('18/10/16','RR/MM/DD'),'nike');
Insert into T_GOODS_DETAIL_IMAGE (IMAGE_ID,GOODS_ID,FILENAME,REG_ID,FILETYPE,CREDATE,CATEGORY) values (347,1,'나이키_코트 버로우 로우 2.jpg','admin','detail_image1',to_date('18/10/16','RR/MM/DD'),'nike');
Insert into T_GOODS_DETAIL_IMAGE (IMAGE_ID,GOODS_ID,FILENAME,REG_ID,FILETYPE,CREDATE,CATEGORY) values (349,2,'나이키_에어맥스 SC 레더.jpg','admin','main_image',to_date('18/10/16','RR/MM/DD'),'nike');
Insert into T_GOODS_DETAIL_IMAGE (IMAGE_ID,GOODS_ID,FILENAME,REG_ID,FILETYPE,CREDATE,CATEGORY) values (350,2,'나이키_에어맥스 SC 레더.jpg','admin','detail_image1',to_date('18/10/16','RR/MM/DD'),'nike');
Insert into T_GOODS_DETAIL_IMAGE (IMAGE_ID,GOODS_ID,FILENAME,REG_ID,FILETYPE,CREDATE,CATEGORY) values (351,3,'나이키_버로우 패딩 겨울 슬리퍼.jpg','admin','main_image',to_date('18/10/16','RR/MM/DD'),'nike');
Insert into T_GOODS_DETAIL_IMAGE (IMAGE_ID,GOODS_ID,FILENAME,REG_ID,FILETYPE,CREDATE,CATEGORY) values (352,3,'나이키_버로우 패딩 겨울 슬리퍼.jpg','admin','detail_image1',to_date('18/10/16','RR/MM/DD'),'nike');
Insert into T_GOODS_DETAIL_IMAGE (IMAGE_ID,GOODS_ID,FILENAME,REG_ID,FILETYPE,CREDATE,CATEGORY) values (353,4,'아디다스_아스티어우먼스.jpg','admin','main_image',to_date('18/10/16','RR/MM/DD'),'adidas');
Insert into T_GOODS_DETAIL_IMAGE (IMAGE_ID,GOODS_ID,FILENAME,REG_ID,FILETYPE,CREDATE,CATEGORY) values (354,4,'아디다스_아스티어우먼스.jpg','admin','detail_image1',to_date('18/10/16','RR/MM/DD'),'adidas');
Insert into T_GOODS_DETAIL_IMAGE (IMAGE_ID,GOODS_ID,FILENAME,REG_ID,FILETYPE,CREDATE,CATEGORY) values (299,5,'아디다스_스탠스미스.jpg','admin','main_image',to_date('18/10/16','RR/MM/DD'),'adidas');
Insert into T_GOODS_DETAIL_IMAGE (IMAGE_ID,GOODS_ID,FILENAME,REG_ID,FILETYPE,CREDATE,CATEGORY) values (300,5,'아디다스_스탠스미스.jpg','admin','detail_image1',to_date('18/10/16','RR/MM/DD'),'adidas');
Insert into T_GOODS_DETAIL_IMAGE (IMAGE_ID,GOODS_ID,FILENAME,REG_ID,FILETYPE,CREDATE,CATEGORY) values (301,6,'아디다스_슈퍼스타.jpg','admin','main_image',to_date('18/10/16','RR/MM/DD'),'adidas');
Insert into T_GOODS_DETAIL_IMAGE (IMAGE_ID,GOODS_ID,FILENAME,REG_ID,FILETYPE,CREDATE,CATEGORY) values (302,6,'아디다스_슈퍼스타.jpg','admin','detail_image1',to_date('18/10/16','RR/MM/DD'),'adidas');
Insert into T_GOODS_DETAIL_IMAGE (IMAGE_ID,GOODS_ID,FILENAME,REG_ID,FILETYPE,CREDATE,CATEGORY) values (303,7,'리복_하이페리움2.jpg','admin','main_image',to_date('18/10/17','RR/MM/DD'),'reebok');
Insert into T_GOODS_DETAIL_IMAGE (IMAGE_ID,GOODS_ID,FILENAME,REG_ID,FILETYPE,CREDATE,CATEGORY) values (304,7,'리복_하이페리움2.jpg','admin','detail_image1',to_date('18/10/17','RR/MM/DD'),'reebok');
Insert into T_GOODS_DETAIL_IMAGE (IMAGE_ID,GOODS_ID,FILENAME,REG_ID,FILETYPE,CREDATE,CATEGORY) values (305,8,'리복_에너져런.jpg','admin','main_image',to_date('18/10/17','RR/MM/DD'),'reebok');
Insert into T_GOODS_DETAIL_IMAGE (IMAGE_ID,GOODS_ID,FILENAME,REG_ID,FILETYPE,CREDATE,CATEGORY) values (306,8,'리복_에너져런.jpg','admin','detail_image1',to_date('18/10/17','RR/MM/DD'),'reebok');
Insert into T_GOODS_DETAIL_IMAGE (IMAGE_ID,GOODS_ID,FILENAME,REG_ID,FILETYPE,CREDATE,CATEGORY) values (307,9,'리복_릿지라이더.jpg','admin','main_image',to_date('18/10/17','RR/MM/DD'),'reebok');
Insert into T_GOODS_DETAIL_IMAGE (IMAGE_ID,GOODS_ID,FILENAME,REG_ID,FILETYPE,CREDATE,CATEGORY) values (308,9,'리복_릿지라이더.jpg','admin','detail_image1',to_date('18/10/17','RR/MM/DD'),'reebok');
Insert into T_GOODS_DETAIL_IMAGE (IMAGE_ID,GOODS_ID,FILENAME,REG_ID,FILETYPE,CREDATE,CATEGORY) values (309,10,'뉴발란스_WL574.jpg','admin','main_image',to_date('18/10/17','RR/MM/DD'),'newbalance');
Insert into T_GOODS_DETAIL_IMAGE (IMAGE_ID,GOODS_ID,FILENAME,REG_ID,FILETYPE,CREDATE,CATEGORY) values (310,10,'뉴발란스_WL574.jpg','admin','detail_image1',to_date('18/10/17','RR/MM/DD'),'newbalance');
Insert into T_GOODS_DETAIL_IMAGE (IMAGE_ID,GOODS_ID,FILENAME,REG_ID,FILETYPE,CREDATE,CATEGORY) values (311,11,'뉴발란스_MS237.jpg','admin','main_image',to_date('18/10/17','RR/MM/DD'),'newbalance');
Insert into T_GOODS_DETAIL_IMAGE (IMAGE_ID,GOODS_ID,FILENAME,REG_ID,FILETYPE,CREDATE,CATEGORY) values (312,11,'뉴발란스_MS237.jpg','admin','detail_image1',to_date('18/10/17','RR/MM/DD'),'newbalance');
Insert into T_GOODS_DETAIL_IMAGE (IMAGE_ID,GOODS_ID,FILENAME,REG_ID,FILETYPE,CREDATE,CATEGORY) values (313,12,'뉴발란스_CM878.jpg','admin','main_image',to_date('18/10/17','RR/MM/DD'),'newbalance');
Insert into T_GOODS_DETAIL_IMAGE (IMAGE_ID,GOODS_ID,FILENAME,REG_ID,FILETYPE,CREDATE,CATEGORY) values (314,12,'뉴발란스_CM878.jpg','admin','detail_image1',to_date('18/10/17','RR/MM/DD'),'newbalance');
Insert into T_GOODS_DETAIL_IMAGE (IMAGE_ID,GOODS_ID,FILENAME,REG_ID,FILETYPE,CREDATE,CATEGORY) values (315,13,'아식스_코트S.jpg','admin','main_image',to_date('18/10/17','RR/MM/DD'),'asic');
Insert into T_GOODS_DETAIL_IMAGE (IMAGE_ID,GOODS_ID,FILENAME,REG_ID,FILETYPE,CREDATE,CATEGORY) values (316,13,'아식스_코트S.jpg','admin','detail_image1',to_date('18/10/17','RR/MM/DD'),'asic');
Insert into T_GOODS_DETAIL_IMAGE (IMAGE_ID,GOODS_ID,FILENAME,REG_ID,FILETYPE,CREDATE,CATEGORY) values (317,14,'아식스_젤-1130.jpg','admin','main_image',to_date('18/10/17','RR/MM/DD'),'asic');
Insert into T_GOODS_DETAIL_IMAGE (IMAGE_ID,GOODS_ID,FILENAME,REG_ID,FILETYPE,CREDATE,CATEGORY) values (339,14,'아식스_젤-1130.jpg','admin','detail_image1',to_date('18/10/21','RR/MM/DD'),'asic');
Insert into T_GOODS_DETAIL_IMAGE (IMAGE_ID,GOODS_ID,FILENAME,REG_ID,FILETYPE,CREDATE,CATEGORY) values (319,15,'아식스_젤 벤쳐6.jpg','admin','main_image',to_date('18/10/17','RR/MM/DD'),'asic');
Insert into T_GOODS_DETAIL_IMAGE (IMAGE_ID,GOODS_ID,FILENAME,REG_ID,FILETYPE,CREDATE,CATEGORY) values (320,15,'아식스_젤 벤쳐6.jpg','admin','detail_image1',to_date('18/10/17','RR/MM/DD'),'asic');
Insert into T_GOODS_DETAIL_IMAGE (IMAGE_ID,GOODS_ID,FILENAME,REG_ID,FILETYPE,CREDATE,CATEGORY) values (321,16,'퓨마_스카이클린.jpg','admin','main_image',to_date('18/10/17','RR/MM/DD'),'puma');
Insert into T_GOODS_DETAIL_IMAGE (IMAGE_ID,GOODS_ID,FILENAME,REG_ID,FILETYPE,CREDATE,CATEGORY) values (322,16,'퓨마_스카이클린.jpg','admin','detail_image1',to_date('18/10/17','RR/MM/DD'),'puma');
Insert into T_GOODS_DETAIL_IMAGE (IMAGE_ID,GOODS_ID,FILENAME,REG_ID,FILETYPE,CREDATE,CATEGORY) values (323,17,'퓨마_스웨이드클래식.jpg','admin','main_image',to_date('18/10/17','RR/MM/DD'),'puma');
Insert into T_GOODS_DETAIL_IMAGE (IMAGE_ID,GOODS_ID,FILENAME,REG_ID,FILETYPE,CREDATE,CATEGORY) values (324,17,'퓨마_스웨이드클래식.jpg','admin','detail_image1',to_date('18/10/17','RR/MM/DD'),'puma');
Insert into T_GOODS_DETAIL_IMAGE (IMAGE_ID,GOODS_ID,FILENAME,REG_ID,FILETYPE,CREDATE,CATEGORY) values (325,18,'퓨마_그래비톤.jpg','admin','main_image',to_date('18/10/20','RR/MM/DD'),'puma');
Insert into T_GOODS_DETAIL_IMAGE (IMAGE_ID,GOODS_ID,FILENAME,REG_ID,FILETYPE,CREDATE,CATEGORY) values (326,18,'퓨마_그래비톤.jpg','admin','detail_image1',to_date('18/10/20','RR/MM/DD'),'puma');
Insert into T_GOODS_DETAIL_IMAGE (IMAGE_ID,GOODS_ID,FILENAME,REG_ID,FILETYPE,CREDATE,CATEGORY) values (327,19,'필라_유니바스티온.jpg','admin','main_image',to_date('18/10/20','RR/MM/DD'),'fila');
Insert into T_GOODS_DETAIL_IMAGE (IMAGE_ID,GOODS_ID,FILENAME,REG_ID,FILETYPE,CREDATE,CATEGORY) values (328,19,'필라_유니바스티온.jpg','admin','detail_image1',to_date('18/10/20','RR/MM/DD'),'fila');
Insert into T_GOODS_DETAIL_IMAGE (IMAGE_ID,GOODS_ID,FILENAME,REG_ID,FILETYPE,CREDATE,CATEGORY) values (330,20,'필라 자가토.jpg','admin','main_image',to_date('18/10/20','RR/MM/DD'),'fila');
Insert into T_GOODS_DETAIL_IMAGE (IMAGE_ID,GOODS_ID,FILENAME,REG_ID,FILETYPE,CREDATE,CATEGORY) values (331,20,'필라 자가토.jpg','admin','detail_image1',to_date('18/10/20','RR/MM/DD'),'fila');
Insert into T_GOODS_DETAIL_IMAGE (IMAGE_ID,GOODS_ID,FILENAME,REG_ID,FILETYPE,CREDATE,CATEGORY) values (334,21,'필라_레이폴라이드.jpg','admin','main_image',to_date('18/10/20','RR/MM/DD'),'fila');
Insert into T_GOODS_DETAIL_IMAGE (IMAGE_ID,GOODS_ID,FILENAME,REG_ID,FILETYPE,CREDATE,CATEGORY) values (341,21,'필라_레이폴라이드.jpg','admin','detail_image1',to_date('18/10/21','RR/MM/DD'),'fila');
--------------------------------------------------------
--  DDL for Index SYS_C0010494
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYS_C0010494" ON "T_GOODS_DETAIL_IMAGE" ("IMAGE_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table T_GOODS_DETAIL_IMAGE
--------------------------------------------------------

  ALTER TABLE "T_GOODS_DETAIL_IMAGE" ADD PRIMARY KEY ("IMAGE_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  
Insert into T_SHOPPING_MEMBER (MEMBER_ID,MEMBER_PW,MEMBER_NAME,MEMBER_GENDER,TEL1,TEL2,TEL3,HP1,HP2,HP3,SMSSTS_YN,EMAIL1,EMAIL2,EMAILSTS_YN,ZIPCODE,ROADADDRESS,JIBUNADDRESS,NAMUJIADDRESS,MEMBER_BIRTH_Y,MEMBER_BIRTH_M,MEMBER_BIRTH_D,MEMBER_BIRTH_GN,JOINDATE,DEL_YN,ADMIN_YN,MEMBER_POINT) values ('admin','1212','어드민','101','02','1111','2222','010','1111','2222','Y','admin','test.com,non','Y','06253','서울 강남구 강남대로 298 (역삼동)','서울 강남구 역삼동 838','럭키빌딩 101호','2000','5','10','2',to_date('18/10/16','RR/MM/DD'),'N','Y',7500);
Insert into T_SHOPPING_MEMBER (MEMBER_ID,MEMBER_PW,MEMBER_NAME,MEMBER_GENDER,TEL1,TEL2,TEL3,HP1,HP2,HP3,SMSSTS_YN,EMAIL1,EMAIL2,EMAILSTS_YN,ZIPCODE,ROADADDRESS,JIBUNADDRESS,NAMUJIADDRESS,MEMBER_BIRTH_Y,MEMBER_BIRTH_M,MEMBER_BIRTH_D,MEMBER_BIRTH_GN,JOINDATE,DEL_YN,ADMIN_YN,MEMBER_POINT) values ('lee','1212','이병승','101','02','1111','2222','010','2222','3333','Y','lee','test.com,non','Y','13547','경기 성남시 분당구 고기로 25 (동원동)','경기 성남시 분당구 동원동 79-1','럭키빌딩 101호','2000','5','10','2',to_date('18/10/23','RR/MM/DD'),'N','N',0);
Insert into T_SHOPPING_MEMBER (MEMBER_ID,MEMBER_PW,MEMBER_NAME,MEMBER_GENDER,TEL1,TEL2,TEL3,HP1,HP2,HP3,SMSSTS_YN,EMAIL1,EMAIL2,EMAILSTS_YN,ZIPCODE,ROADADDRESS,JIBUNADDRESS,NAMUJIADDRESS,MEMBER_BIRTH_Y,MEMBER_BIRTH_M,MEMBER_BIRTH_D,MEMBER_BIRTH_GN,JOINDATE,DEL_YN,ADMIN_YN,MEMBER_POINT) values ('hong','1212','홍길동','101','02','1111','2222','010','1111','2222','Y','hong','gmail.com','Y','06253','서울 강남구 강남대로 298 (역삼동)','서울 강남구 역삼동 838','럭키빌딩 101호','2000','5','10','2',to_date('18/10/16','RR/MM/DD'),'N','N',0);
Insert into T_SHOPPING_MEMBER (MEMBER_ID,MEMBER_PW,MEMBER_NAME,MEMBER_GENDER,TEL1,TEL2,TEL3,HP1,HP2,HP3,SMSSTS_YN,EMAIL1,EMAIL2,EMAILSTS_YN,ZIPCODE,ROADADDRESS,JIBUNADDRESS,NAMUJIADDRESS,MEMBER_BIRTH_Y,MEMBER_BIRTH_M,MEMBER_BIRTH_D,MEMBER_BIRTH_GN,JOINDATE,DEL_YN,ADMIN_YN,MEMBER_POINT) values ('kim','1212','김유신','101','02','1111','2222','010','2222','3333','Y','kim','jweb.com','Y','13547','경기 성남시 분당구 고기로 25 (동원동)','경기 성남시 분당구 동원동 79-1','럭키빌딩 101호','2000','5','10','2',to_date('18/10/23','RR/MM/DD'),'N','N',0);
Insert into T_SHOPPING_MEMBER (MEMBER_ID,MEMBER_PW,MEMBER_NAME,MEMBER_GENDER,TEL1,TEL2,TEL3,HP1,HP2,HP3,SMSSTS_YN,EMAIL1,EMAIL2,EMAILSTS_YN,ZIPCODE,ROADADDRESS,JIBUNADDRESS,NAMUJIADDRESS,MEMBER_BIRTH_Y,MEMBER_BIRTH_M,MEMBER_BIRTH_D,MEMBER_BIRTH_GN,JOINDATE,DEL_YN,ADMIN_YN,MEMBER_POINT) values ('aaa','1212','안병호','101','없음',null,null,'010',null,null,'Y',null,',non','Y',null,null,null,null,'1999','5','10','2',to_date('23/01/11','RR/MM/DD'),'N','N',21950);

commit;